language: node_js
sudo: yes
node_js:
  - '4.0'
  - 'stable'
services:
  - mysql
before_install:
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('161301') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo mysql_upgrade
  - sudo service mysql restart
  - mysql -e "CREATE DATABASE modelar;"
  - mysql -u root -p 161301 --default-character-set=utf8 modelar < ./modelar.sql