language: node_js
sudo: false
node_js:
  - '4.0'
  - 'stable'
services:
  - mysql
before_install:
  mysql -e "CREATE DATABASE modelar;"
  mysql -u root --default-character-set=utf8 modelar < ./modelar.sql